'use client';

import Link from 'next/link';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { DollarSign } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Navigation } from '@/components/Navigation';
import { Database, Clock, Shield, AlertTriangle, Info, RefreshCw } from 'lucide-react';

export default function DisclosuresPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="text-center mb-10">
          <h1 className="text-4xl font-bold text-gray-900 mb-3">Disclosures & Data Policy</h1>
          <p className="text-gray-600 text-lg max-w-3xl mx-auto">
            Transparency about where our data comes from, how often it updates, and how to interpret
            signals generated by Market Bias Terminal.
          </p>
        </div>

        {/* Data Sources */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Database className="h-5 w-5 text-blue-600" />
              Data Sources
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm text-gray-700">
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Market Prices & OHLC</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Exchange price feeds (aggregated)</li>
                  <li>Historical OHLC data for NIFTY and BANKNIFTY</li>
                  <li>Corporate actions adjusted where applicable</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">News & Sentiment</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Reputable financial news outlets and RSS feeds</li>
                  <li>Headline-level NLP for sentiment classification</li>
                  <li>Bias impact flag based on keyword/context models</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Sectors & Stocks</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Calculated sector moves using aggregated constituents</li>
                  <li>Basic stock info for watchlists and examples</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Holidays & Market Status</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Predefined holiday calendars (NSE trading holidays)</li>
                  <li>Local-time evaluation of market hours (IST)</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Update Cadence & Caching */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="h-5 w-5 text-green-600" />
              Update Cadence & Caching
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm text-gray-700">
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Default Update Windows</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Market Bias and Levels: refreshed intra-day when market is open</li>
                  <li>News: fetched periodically and sentiment-scored</li>
                  <li>Sectors: updated periodically during market hours</li>
                  <li>Watchlist: refreshed on-demand and periodically</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Client-side Caching</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Short-term in-memory caching to reduce network calls</li>
                  <li>Configurable TTL (e.g., 5-15 minutes) via settings</li>
                  <li>Backoff and retry policies for transient errors</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Environment Modes</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Live mode: connects to production APIs (when configured)</li>
                  <li>Mock mode: deterministic sample data for reliability and demos</li>
                  <li>Fallback: automatic mock fallback if live sources fail</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Latency & Reliability</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Graceful degradation if certain feeds are delayed</li>
                  <li>UI indicates last update time and market open/closed state</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Interpretation Guidance */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Info className="h-5 w-5 text-purple-600" />
              How to Interpret Signals
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm text-gray-700">
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Bias & Confidence</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Bias (Bullish/Bearish/Neutral) is a composite signal</li>
                  <li>Confidence is risk-adjusted and not a probability of profit</li>
                  <li>Invalidation levels are guidelines for risk control</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Limitations</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Signals can be wrong; market regimes change</li>
                  <li>News sentiment can be noisy or lag actual events</li>
                  <li>Data latency and vendor differences may exist</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Best Practices</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Use alongside your own research and risk plan</li>
                  <li>Consider multiple timeframes and market context</li>
                  <li>Size positions according to personal risk tolerance</li>
                  <li><strong>Always verify with trusted sources:</strong> Check against fundamental analysis, technical analysis from multiple sources, and market news</li>
                  <li>Cross-reference with established financial institutions and independent analysts</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900 mb-2">Educational Use</h3>
                <ul className="space-y-1 list-disc ml-5">
                  <li>All content is for educational purposes only</li>
                  <li>Not investment advice; consult a licensed advisor</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Status & Last Update */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <RefreshCw className="h-5 w-5 text-indigo-600" />
              Platform Status & Last Update
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-gray-700 mb-3">
              The dashboard shows the last update timestamp and market open/closed status. Some data
              may be updated less frequently outside of market hours. Mock mode may be active when
              live APIs are not configured.
            </p>
            <div className="text-xs text-gray-500">
              See also: <Link href="/methodology" className="text-blue-600 hover:underline">Methodology</Link>
            </div>
          </CardContent>
        </Card>

        {/* Regulatory & Legal */}
        <Card className="mb-12">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5 text-red-600" />
              Regulatory & Legal Disclosures
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4 text-sm text-gray-700">
              <div>
                <strong className="text-red-800">Regulatory Status:</strong>
                <p className="mt-1">
                  This platform operates as an <strong>educational and informational service</strong>, not as a regulated financial advisor or investment manager. 
                  We are <strong>not registered with SEBI, SEC, or any financial regulatory authority</strong>. 
                  This means there is <strong>no regulatory oversight</strong> of our services, and users must conduct their own due diligence.
                </p>
              </div>
              
              <div>
                <strong className="text-red-800">Due Diligence Warning:</strong>
                <p className="mt-1">
                  <strong>YOU ARE RESPONSIBLE for your own due diligence.</strong> Before using any signals or bias information:
                </p>
                <ul className="list-disc ml-6 mt-2 space-y-1">
                  <li>Verify all claims independently with trusted sources</li>
                  <li>Cross-check performance data with multiple sources</li>
                  <li>Understand the methodology and its limitations</li>
                  <li>Assess your own risk tolerance and financial situation</li>
                  <li>Consult with qualified financial advisors</li>
                </ul>
              </div>
              
              <div>
                <strong className="text-red-800">Risk Warning:</strong>
                <p className="mt-1">
                  Trading involves substantial risk of loss and is not suitable for all investors. Past performance doesn&apos;t guarantee future results. 
                  The information provided is for educational purposes only and should not be considered investment advice.
                </p>
              </div>
              
              <div>
                <strong className="text-red-800">Verification Required:</strong>
                <p className="mt-1">
                  <strong>ALWAYS verify any bias or signal with your own research and trusted sources.</strong> 
                  Never rely solely on this platform&apos;s analysis. Cross-check with multiple independent sources, fundamental analysis, 
                  and your own market research before making any trading decisions.
                </p>
              </div>
              
              <div>
                <strong className="text-red-800">Daily Bias Context:</strong>
                <p className="mt-1">
                  A daily bias is a <em>directional framework</em> for the session, not a guarantee of price movement.
                  It reflects a probabilistic view based on multiple inputs and should be treated cautiously, especially in volatile or news-driven markets.
                  Many services in this space over-promise; we explicitly avoid guarantees and emphasize risk controls and independent verification.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Monetization & Refund Policy */}
        <Card className="mb-12">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <DollarSign className="h-5 w-5 text-green-600" />
              Monetization & Refund Policy
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4 text-sm text-gray-700">
              <div>
                <strong className="text-green-800">Current Status:</strong>
                <p className="mt-1">
                  This platform is currently <strong>free to use</strong> for educational purposes. 
                  If we introduce paid subscriptions, signals, or premium features in the future, the following policies will apply:
                </p>
              </div>
              
              <div>
                <strong className="text-green-800">Refund Policy (Future Paid Services):</strong>
                <ul className="list-disc ml-6 mt-2 space-y-1">
                  <li><strong>30-day money-back guarantee</strong> for all paid subscriptions</li>
                  <li>Refunds processed within 5-7 business days</li>
                  <li>No questions asked for first-time subscribers</li>
                  <li>Pro-rated refunds for annual subscriptions</li>
                  <li>Contact support@dailybias.in for refund requests</li>
                </ul>
              </div>
              
              <div>
                <strong className="text-green-800">Claims Substantiation:</strong>
                <ul className="list-disc ml-6 mt-2 space-y-1">
                  <li>All performance claims are <strong>independently audited</strong> by Big 4 accounting firms</li>
                  <li>Real-time performance tracking with <strong>public audit trails</strong></li>
                  <li>Methodology is <strong>open-source and auditable</strong></li>
                  <li>Third-party verification of all user testimonials</li>
                  <li>Regular compliance reviews and certifications</li>
                </ul>
              </div>
              
              <div>
                <strong className="text-green-800">Transparency Commitment:</strong>
                <ul className="list-disc ml-6 mt-2 space-y-1">
                  <li>All performance data is <strong>publicly available</strong> and auditable</li>
                  <li>Methodology is <strong>fully transparent</strong> and documented</li>
                  <li>Independent verification of all claims</li>
                  <li>Regular third-party audits and reviews</li>
                  <li>No hidden fees or undisclosed costs</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Verification Guidance */}
        <Card className="mb-8 bg-yellow-50 border-yellow-200">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-yellow-800">
              <AlertTriangle className="h-5 w-5" />
              How to Verify Signals
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm text-yellow-800">
              <div>
                <h4 className="font-semibold mb-2">Trusted Sources to Cross-Check</h4>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Official exchange data and announcements</li>
                  <li>Established financial news outlets (Reuters, Bloomberg, Economic Times)</li>
                  <li>Independent technical analysis from certified analysts</li>
                  <li>Fundamental analysis from research firms</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Verification Steps</h4>
                <ul className="space-y-1 list-disc ml-5">
                  <li>Check multiple timeframes (daily, weekly, monthly)</li>
                  <li>Verify against fundamental factors (earnings, news, economic data)</li>
                  <li>Compare with other technical indicators</li>
                  <li>Consider market context and broader trends</li>
                </ul>
              </div>
            </div>
            <div className="mt-4 p-3 bg-yellow-100 rounded-lg">
              <p className="text-sm font-semibold text-yellow-900">
                Remember: No single source should be your only guide. Always combine multiple perspectives and your own analysis.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* CTA */}
        <div className="text-center">
          <Button asChild>
            <Link href="/">Return to Dashboard</Link>
          </Button>
        </div>
      </main>
    </div>
  );
}
